name: CI

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Run Tests
        run: dotnet test
      - name: Install Frontend
        working-directory: agent13-frontend
        run: npm install

      - name: Build Frontend
        working-directory: agent13-frontend
        run: npm run build
